
        <?php 
        $titulo_mensaje = $mensaje ?? "null"; 
        $icon_mensaje = $icono ?? "null";
        ?>

    <section class="check-in-section hide-check-in-box">
    
        <div class="check-in-container">
            <dotlottie-player 
                src="/imagenes/lordicon json/<?php echo $icon_mensaje; ?>" 
                background="transparent" 
                speed="0.3" 
                style="width: 150px; height: 150px;" 
                loop 
                autoplay>
            </dotlottie-player>
            <span class="check-in-text"><?php echo $titulo_mensaje; ?></span>
            
        
      
    </section>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Roboto:wght@400;500&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0');


        .show-check-in-box{
            display: flex !important; 
        }

        .hide-check-in-box{
            display: none !important;
        }

        .check-in-section{
            position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 9999; /* Muy alto para tapar todo */
    
    /* Centramos el contenido (la caja blanca) con Flexbox */
    display: flex;
    justify-content: center;
    align-items: center;
    
    /* El fondo oscuro va aquí directamente */
    background-color: rgba(0, 0, 0, 0.5);
    backdrop-filter: blur(5px);
    -webkit-backdrop-filter: blur(5px);
            
        }
        .check-in-section::before,
        .check-in-section::after{
            display: none;
        }


        .check-in-container{
            background-color: #fff;
    width: 90%;          /* En celular ocupa el 90% */
    max-width: 500px;    /* En PC no pasa de 500px */
    padding: 30px 20px;  /* Un poco de aire interno */
    border-radius: 12px; /* Bordes redondeados */
    
    /* Sombras y animación */
    box-shadow: 0px 10px 25px rgba(0,0,0,0.2);
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 20px;
    position: relative;
    
    /* La animación de entrada */
    -webkit-animation: slide-in-blurred-top 0.6s cubic-bezier(0.230, 1.000, 0.320, 1.000) both;
    animation: slide-in-blurred-top 0.6s cubic-bezier(0.230, 1.000, 0.320, 1.000) both;
        }
        
        .check-in-text{
            font-size: 1.5rem;
            font-weight: 600;
            color: #0A1931;
            font-family: 'Montserrat', sans-serif;
            text-align: center;
            overflow-wrap: break-word;
        }

                    /* ----------------------------------------------
            * Generated by Animista on 2025-12-30 0:52:9
            * Licensed under FreeBSD License.
            * See http://animista.net/license for more info. 
            * w: http://animista.net, t: @cssanimista
            * ---------------------------------------------- */

            /**
            * ----------------------------------------
            * animation slide-in-blurred-top
            * ----------------------------------------
            */
            @-webkit-keyframes slide-in-blurred-top {
            0% {
                -webkit-transform: translateY(-1000px) scaleY(2.5) scaleX(0.2);
                        transform: translateY(-1000px) scaleY(2.5) scaleX(0.2);
                -webkit-transform-origin: 50% 0%;
                        transform-origin: 50% 0%;
                -webkit-filter: blur(40px);
                        filter: blur(40px);
                opacity: 0;
            }
            100% {
                -webkit-transform: translateY(0) scaleY(1) scaleX(1);
                        transform: translateY(0) scaleY(1) scaleX(1);
                -webkit-transform-origin: 50% 50%;
                        transform-origin: 50% 50%;
                -webkit-filter: blur(0);
                        filter: blur(0);
                opacity: 1;
            }
            }
            @keyframes slide-in-blurred-top {
            0% {
                -webkit-transform: translateY(-1000px) scaleY(2.5) scaleX(0.2);
                        transform: translateY(-1000px) scaleY(2.5) scaleX(0.2);
                -webkit-transform-origin: 50% 0%;
                        transform-origin: 50% 0%;
                -webkit-filter: blur(40px);
                        filter: blur(40px);
                opacity: 0;
            }
            100% {
                -webkit-transform: translateY(0) scaleY(1) scaleX(1);
                        transform: translateY(0) scaleY(1) scaleX(1);
                -webkit-transform-origin: 50% 50%;
                        transform-origin: 50% 50%;
                -webkit-filter: blur(0);
                        filter: blur(0);
                opacity: 1;
            }
            }

    </style>

        <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
